### ISSUE TITLE
Create Game in Database

### ISSUE THREAD

**Issue by Elinriel** [sopra-fs21-group-05/group-05-server#34]
- [x] Create Game entity
- [x] Create Game repository
- [x] Games can be saved to the database
- [x] Games can be retrieved from the database

Time estimate: 2h
This task is part of user story #3

**Comment by DineshKoushik** [comment]
@Elinriel , I'll give this a try, please mention what fields you want me to put in game entity

**Comment by Elinriel** [comment]
> @Elinriel , I'll give this a try, please mention what fields you want me to put in game entity

Sorry, this is part of a university project, so we need to do everything ourselves!
