### ISSUE TITLE
User unit tests

### ISSUE THREAD

**Issue by Elinriel** [sopra-fs21-group-05/group-05-server#44]
- [x] Create unit tests for the user service

Time estimate: 3h
This task is part of user story #4

**Comment by DineshKoushik** [comment]
@Elinriel , I'll try this, Can you assign this to me?

**Comment by Elinriel** [comment]
> @Elinriel , I'll try this, Can you assign this to me?

Sorry, this is part of a university project, so we need to do everything ourselves!
